name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
      name: Deploy
      runs-on: ubuntu-latest

      steps: 
        - name: Checkout
          uses: actions/checkout@v1

        - name: Add remote origin
          run: git remote add heroku https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git
        - name: Set ENV Variables
          run: heroku config:set VIDEO_API_API_KEY=${{ secrets.VIDEO_API_API_KEY }} VIDEO_API_API_SECRET=${{ secrets.VIDEO_API_API_SECRET }} 

        - name: Deploy backend to heroku
          run: git push --force heroku `git subtree split --prefix server HEAD`:master
